name: Deploy Artifact on Maven then merge on main

on:
  push:
    branches:
      - deploy

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
      - name: configure settings
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [
              {
                "id": "ossrh",
                "username": "${{ env.OSSRH_USERNAME }}", 
                "password": "${{ env.OSSRH_PASSWORD }}"
              }
            ]
      - name: Deploy artifact on maven
        run: mvn --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ env.PASSPHRASE }}  clean deploy 
      - name: Merge deploy -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: deploy
          target_branch: main
          github_token: ${{ env.GITHUB_TOKEN }}
