name: Run tests

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run tests
        run: mvn clean test